version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  discovery-service:
    build: ./discovery-server
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-service
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  plan-service:
    build: ./plan-service
    container_name: plan-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-service
      - mongo
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
      - user-service
      - plan-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always
