spring:
  application:
    name: plan-service
  profiles:
    active: default
  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
